import os
import numpy as np
import time
import numpy as np
import pandas as pd
from sklearn.manifold import Isomap as IS
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt


def plot(dataset, filename):
    path = '../data/' + dataset
    emb = np.array(pd.read_csv(path + '/' + filename + '.csv',header=None,sep=' '))
    X = IS(n_components=2,n_jobs=-1).fit_transform(emb)
    # X = TSNE(n_components=2).fit_transform(emb)
    print X.shape
    
    # Save two-dimensional embeddings generated by isomap
    np.savetxt(path + '/' + filename + '_ISOMAP.csv',X,fmt='%.6e')
    
    label = pd.read_csv(path+'/label.csv',sep='\n',header=None)
    label = np.array(label[0])
    print len(label)

    cat = set(label)
    print cat,' classes are there'

    clr='rgb'

    for c in [0, 1, 2]:
        points = X[label==c]
        print c,sum(label==c), clr[c]
        plt.plot(list(points[:,0]),list(points[:,1]) , clr[c]+'.', markersize=0.5,marker='.' )
    plt.axis('off')
    plt.savefig(dataset + '_' + filename + '.png',format='png')
    plt.show()
    plt.clf()
    return X
    
    

